### ISSUE TITLE
Testing Needed

### ISSUE THREAD

**Issue by BenRGarcia** [BenRGarcia/Tune-Up#27]
1. User can login successfully, uid and displayName retrieved
2. User can create a new car (with year/make/model/mileage)
3. User can create additional cars
4. User can delete a car
5. User can update mileage of car
6. User can update last time maintenance performed (on each of 5: oil/tire/brakes/inspection/wipers)
7. User can update the default maintenance intervals (on each of 5: oil/tire/brakes/inspection/wipers)
8. User car object data can be retrieved from the database
9. ... probably some other things I haven't thought of yet

**Comment by melissarburnham** [comment]
9. User can find available auto shops in relation to current location.
10. User can click on location marker to pull up information and directions.
